name: ncnn_example
description: Demonstrates how to use the ncnn plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.1"

dependencies:
  camera: ^0.10.1
  flutter:
    sdk: flutter
  image: ^3.3.0
  ncnn:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
