name: ncnn_android

on:
  pull_request:
    paths:
      - ".github/workflows/ncnn_android.yaml"
      - "ncnn_android/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ncnn_android.yaml"
      - "ncnn_android/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.1
      working_directory: ncnn_android
