name: ncnn_platform_interface

on:
  pull_request:
    paths:
      - ".github/workflows/ncnn_platform_interface.yaml"
      - "ncnn_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ncnn_platform_interface.yaml"
      - "ncnn_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.1
      working_directory: ncnn_platform_interface
